/**
 * Exact mirror of the build agent's immutable-path rule
 * (packages/agentic-codegen/src/flowstarter/pi-sdk.ts —
 * `PACKAGE_MANAGER_DIRECTORIES`, `PACKAGE_MANAGER_FILES`, `PNPMFILE_STEM`,
 * `isPackageManagerConfigPath`, `assertMutableAgentPath`'s `alwaysDenied`
 * branch). That module decides what the build agent may write inside a
 * generated site's own worktree. This module decides the SAME thing for
 * the router's operator-session control plane, which materialises the
 * same kind of worktree and then hands an interactive Claude Code
 * session the keys to it. If the two rules drift, a path the build agent
 * refuses becomes editable the moment a human (or an agent acting as
 * one) drives the editor instead — same directory, weaker guard, no
 * reason for the difference. `router/test/agent-boundary.test.ts` reads
 * pi-sdk.ts off disk and pins the two literal sets below so an upstream
 * addition cannot go unnoticed here.
 *
 * Keep this file's checks, and their ORDER, identical to
 * `assertMutableAgentPath`'s `alwaysDenied` list. pi-sdk also has a
 * `preview`-mode allowlist (content/data/styles-only) layered on top of
 * `alwaysDenied` — that is NOT mirrored here on purpose: an operator
 * session may edit anything mutable in the worktree (whole features, new
 * pages), not just content.
 */

/**
 * Directories a package manager owns outright. `.pnpm` is the virtual
 * store every dependency is actually resolved from and `.yarn` holds
 * Yarn's plugins and its bundled releases, which are plain JavaScript
 * that Yarn executes. Neither is site content under any reading. Copied
 * verbatim from pi-sdk.ts — do not hand-edit without checking it still
 * matches there.
 */
export const PACKAGE_MANAGER_DIRECTORIES: ReadonlySet<string> = new Set([
  ".pnpm",
  ".yarn",
]);

/**
 * Files a package manager reads before it installs anything: manifests,
 * workspace definitions, registry configuration and lockfiles, for every
 * package manager a generated site might plausibly be handed to. Copied
 * verbatim from pi-sdk.ts — do not hand-edit without checking it still
 * matches there.
 */
export const PACKAGE_MANAGER_FILES: ReadonlySet<string> = new Set([
  "package.json",
  "pnpm-workspace.yaml",
  "pnpm-workspace.yml",
  ".npmrc",
  ".yarnrc",
  ".yarnrc.yml",
  ".yarnrc.yaml",
  ".bunfig.toml",
  "bunfig.toml",
  "package-lock.json",
  "npm-shrinkwrap.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "bun.lockb",
  "bun.lock",
]);

/**
 * `.pnpmfile.cjs` and every extension pnpm will load it under. Matched
 * as a prefix rather than listed one by one, because the thing that
 * matters is the stem: pnpm resolves the module, and the module system
 * decides the suffix.
 */
export const PNPMFILE_STEM = ".pnpmfile";

/**
 * True for any path that is part of the package manager's own
 * configuration. Same implementation as pi-sdk.ts's function of the same
 * name — see there for the full rationale (short version: the install
 * step is the one step allowed outbound network, so a file the agent
 * wrote that decides what that step runs and where it talks to is the
 * whole of the escape). Checked on every path segment, not only the
 * root, because pnpm reads an `.npmrc` out of each package directory it
 * installs — a nested one is not a weaker version of a root one.
 */
export function isPackageManagerConfigPath(path: string): boolean {
  const segments = path
    .replace(/\\/g, "/")
    .toLowerCase()
    .split("/")
    .filter(Boolean);
  return segments.some(
    (segment) =>
      PACKAGE_MANAGER_DIRECTORIES.has(segment) ||
      PACKAGE_MANAGER_FILES.has(segment) ||
      segment === PNPMFILE_STEM ||
      segment.startsWith(`${PNPMFILE_STEM}.`),
  );
}

/**
 * Plain-words reason a path is immutable for the coding agent, or null
 * if the path is fair game. Same checks, same order, as pi-sdk's
 * `alwaysDenied` branch — the only difference is the return shape (a
 * reason string here instead of a thrown Error there), because this
 * function backs both the settings.json deny list below and a
 * human-readable explanation, not just a guard that throws.
 */
export function immutableAgentPathReason(path: string): string | null {
  const normalized = path.toLowerCase();
  const segments = normalized.split("/");
  const basename = segments.at(-1) ?? "";

  if (segments.includes(".git")) {
    return "inside .git — the coding agent must never rewrite the repository's own history";
  }
  if (segments.includes("node_modules")) {
    return "inside node_modules — installed dependencies, not site content";
  }
  if (segments.includes("dist")) {
    return "inside dist — build output, regenerated by the build, not source";
  }
  if (segments.includes(".astro")) {
    return "inside .astro — Astro's own cache directory, regenerated by the build, not source";
  }
  if (isPackageManagerConfigPath(normalized)) {
    return "part of the package manager's own configuration — it decides what the install step runs and where it talks to";
  }
  // Lockfiles this rule has not been taught the name of yet. Kept on the
  // basename alone rather than a fixed list of known lockfile names — the
  // accepted cost is that a page about a locksmith is ALSO denied (see
  // the "locksmith" case in agent-boundary.test.ts, mirrored from
  // upstream's own comment on this line).
  if (basename.includes("lock")) {
    return 'basename contains "lock" — treated as a lockfile, which pins what actually gets installed';
  }
  if (basename.startsWith(".env")) {
    return "looks like an environment file — environment files can carry secrets";
  }
  if (basename.includes("secret")) {
    return 'basename contains "secret"';
  }
  if (basename.includes("credential")) {
    return 'basename contains "credential"';
  }
  if (basename === "astro.config.mjs" || basename === "astro.config.js") {
    return "astro.config decides how the whole site builds";
  }
  if (basename.startsWith("vite.config")) {
    return "vite.config decides how the whole site builds";
  }
  if (basename.startsWith("next.config")) {
    return "next.config decides how the whole site builds";
  }
  if (segments.includes(".github")) {
    return "inside .github — workflows run with the repository's own permissions, not the agent's";
  }
  return null;
}

/**
 * Structural denials `assertMutableAgentPath` checks inline rather than
 * through a named, exported set like the two above. Collected here only
 * so `CLAUDE_DENY_RULES` below can be generated from data instead of
 * hand-typed a second time — see the file header for why a hand-typed
 * second copy is exactly the failure mode this file exists to prevent.
 */
const STRUCTURAL_DENIED_DIRECTORIES: readonly string[] = [
  ".git",
  "node_modules",
  "dist",
  ".astro",
  ".github",
];

const STRUCTURAL_DENIED_FILES: readonly string[] = [
  "astro.config.mjs",
  "astro.config.js",
];

/** basename-substring / basename-prefix denials, expressed as globs. */
const STRUCTURAL_DENIED_BASENAME_GLOBS: readonly string[] = [
  ".env*",
  "*lock*",
  "*secret*",
  "*credential*",
  "vite.config*",
  "next.config*",
];

/**
 * Claude Code permission `deny` rules, one per entry in
 * `PACKAGE_MANAGER_DIRECTORIES`, `PACKAGE_MANAGER_FILES`, `PNPMFILE_STEM`,
 * and the structural lists above — generated, not hand-typed, so a new
 * denied name added to any of those sets cannot be forgotten here.
 * `.env*` additionally denies Read, not just Edit: an agent that cannot
 * write an env file but can still read one can still read out whatever
 * secret is in it.
 */
export const CLAUDE_DENY_RULES: readonly string[] = [
  ...[...PACKAGE_MANAGER_DIRECTORIES, ...STRUCTURAL_DENIED_DIRECTORIES].map(
    (dir) => `Edit(./${dir}/**)`,
  ),
  ...[...PACKAGE_MANAGER_FILES, ...STRUCTURAL_DENIED_FILES].map(
    (file) => `Edit(./${file})`,
  ),
  `Edit(./${PNPMFILE_STEM}*)`,
  ...STRUCTURAL_DENIED_BASENAME_GLOBS.flatMap((glob) =>
    glob === ".env*" ? [`Read(./${glob})`, `Edit(./${glob})`] : [`Edit(./${glob})`],
  ),
];

/**
 * The `.claude/settings.json` text materialized into every operator
 * worktree. It pins the session: the agent may do anything a coding
 * agent can inside the worktree (whole features, new pages) but may not
 * reach outside it (`additionalDirectories: []`) or rewrite what decides
 * how the site installs and builds (`CLAUDE_DENY_RULES`), and may not
 * pull in a project-level MCP server it was never meant to have
 * (`enableAllProjectMcpServers: false`).
 */
export function editorSettingsJson(): string {
  return JSON.stringify(
    {
      permissions: {
        deny: CLAUDE_DENY_RULES,
        additionalDirectories: [],
      },
      enableAllProjectMcpServers: false,
    },
    null,
    2,
  );
}
