#!/usr/bin/env bash
# Nightly backup of everything on this Hetzner host that is not reproducible
# from git: every Supabase CLI stack's Postgres database, the self-hosted
# Cal.com database, the client sites tree, and /etc/flowstarter (env files,
# TLS keys, and this script's own gpg passphrase file — which is excluded
# from the tarball it protects, see below).
#
# WHY Cal is in that list. `flowstarter-cal-db` holds every client's booking
# page — their event types, their availability, their connected calendars —
# and every booking their visitors have made. None of it exists anywhere else:
# it is not in the product's Supabase database, it is not in git, and it cannot
# be regenerated by re-running the provisioner, because a re-run would produce
# empty booking pages and lose the appointments. Losing this volume means
# telling clients their bookings are gone. It is dumped exactly like the
# Supabase databases, into the same dated directory and the same manifest, so
# one restore drill covers both -- and, like every other database dump, it is
# now encrypted (see below), where before this fix only the /etc tarball was.
#
# This backs up the STAGING/PROD BOX's local state. The hosted production
# Supabase project is a separate thing, backed up by
# scripts/supabase-prod-backup.mjs at the repo root, run by hand from an
# operator's machine, never from this host or from CI.
#
# Usage:
#   backup.sh
#
# Meant to run nightly via systemd, see ../systemd/flowstarter-backup.service
# and ../systemd/flowstarter-backup.timer. Run as root: it reads
# /etc/flowstarter and talks to the Docker socket.
#
# Security audit 2026-09-13 (Claude M2; Codex F15) found three problems with
# the backup tree: the database dumps were the one artifact that carried real
# tenant data and were the one artifact NOT encrypted (mode 644, plaintext,
# right next to the encrypted-but-secret-free-anyway /etc tarball); the gpg
# passphrase file lived inside the very directory (/etc/flowstarter) that got
# tarred and encrypted with it, so a copy of the passphrase-derived ciphertext
# of the passphrase itself shipped inside the artifact it protects; and there
# was no restrictive umask, so a fresh dated directory or dump could inherit
# a permissive one from the environment instead of getting 0600/0700 by
# construction. All three are fixed here:
#
#   - every database dump is now streamed straight into encryption (see
#     backup-crypto.sh, sourced below) — never written to disk in plaintext —
#     with the same age-else-gpg tool selection the /etc tarball already used.
#   - the /etc tarball is itself streamed straight into encryption too (tar
#     piped into the encryptor, never a plaintext tarball on disk even
#     momentarily), and BACKUP_GPG_PASSPHRASE_FILE is excluded from what tar
#     reads whenever it lives inside FLOWSTARTER_ETC_DIR.
#   - `umask 0077` at the top of main(), plus an explicit `chmod 0700` on
#     $BACKUP_ROOT and the dated directory and `chmod 0600` on every artifact
#     right after it is produced, so the permission is correct even if this
#     script ever runs with a looser inherited umask.
#   - a cleanup-on-failure trap removes any partially-written artifact
#     (`*.partial`) so a mid-run failure — a dead docker daemon, a full disk,
#     an interrupted encrypt — never leaves a file that looks finished but
#     is not, encrypted or otherwise.
#
# Decisions inherited unchanged from before this fix, still accurate:
#   - age, if `age` is on PATH. The recipient (public key) comes from
#     BACKUP_AGE_RECIPIENT_FILE (a file holding one age public key, the
#     format `age -R` expects) or, if that is unset, BACKUP_AGE_RECIPIENT
#     (the public key given inline). One of the two must be set when age is
#     the tool in use.
#   - gpg --symmetric, if age is not on PATH. The passphrase comes from a
#     file named by BACKUP_GPG_PASSPHRASE_FILE, which must exist and be mode
#     600. The script refuses to run rather than fall back to an interactive
#     prompt or a weaker default.
# The choice between the two is made at runtime by checking `command -v
# age`, never hardcoded, so a box that later installs age switches over with
# no script change. See backup-crypto.sh for the shared implementation
# restore.sh also uses.
#
# Env overrides (documented defaults, never bare numbers or paths in the
# logic below, the same idea as capEur() in
# apps/flowstarter-main/src/lib/ai/funnel-cost.ts applied to retention counts):
#   BACKUP_ROOT                 root of the backup tree, default /var/backups/flowstarter
#   SITES_DIR                   client sites tree, default /var/www/sites
#   FLOWSTARTER_ETC_DIR         secrets directory, default /etc/flowstarter
#   PG_DUMP_ARGS                extra flags appended to `pg_dump`, default none
#   BACKUP_DB_CONTAINER_PATTERN extended regex matched against `docker ps`
#                                names to decide what gets dumped, default
#                                `^supabase_db_|^flowstarter-cal-db$` (every
#                                Supabase CLI stack, plus the Cal database).
#                                No container name is hardcoded in the logic
#                                below; a second Cal instance or a renamed one
#                                is a change to this variable, not to the script
#   BACKUP_AGE_RECIPIENT_FILE   path to a file holding an age public key
#   BACKUP_AGE_RECIPIENT        an age public key given directly (used only
#                                if BACKUP_AGE_RECIPIENT_FILE is unset)
#   BACKUP_GPG_PASSPHRASE_FILE  default /etc/flowstarter/backup-gpg-passphrase
#   BACKUP_KEEP_DAILY           dated directories always kept, default 7
#   BACKUP_KEEP_WEEKLY          weekly directories kept beyond that, default 4
#   BACKUP_S3_BUCKET            bucket/container name; unset skips upload entirely
#   BACKUP_S3_ENDPOINT          S3-compatible endpoint URL (Hetzner Object
#                                Storage, Backblaze B2, etc.), optional
#   BACKUP_S3_PREFIX            key prefix under the bucket, default this host's hostname
#
# Retention rule (see retention_apply() below for the implementation): the
# most recent BACKUP_KEEP_DAILY dated directories are always kept. Beyond
# that window, directories are grouped into consecutive runs of 7 (this job
# runs nightly, so one dated directory is one elapsed day and a run of 7 is
# one elapsed week without needing to parse a weekday or an ISO week number
# out of a directory name), and the oldest survivor of each of the most
# recent BACKUP_KEEP_WEEKLY runs is kept. Everything else is deleted.
#
# S3 upload: uploads with whichever of rclone or aws is on PATH, preferring
# rclone (it is the tool actually installed for this on the Hetzner image;
# aws is the fallback for a box that only has the AWS CLI). With no
# BACKUP_S3_* configuration this step is skipped cleanly, no error. A failed
# upload does NOT undo or re-run the local backup: the dump and tarballs
# already on disk are what restore.sh and a human trust, and a transient
# network blip should not cost a night's local backup. It DOES make the
# overall script exit non-zero, on purpose, once every local step has
# finished: a nightly timer's failed run shows up in `systemctl status` /
# the journal, which is the only way an operator finds out the remote copy
# is stale before they need it.
#
# Never prints a secret (passphrase, S3 key, age recipient) to stdout/stderr
# at any point.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./backup-crypto.sh
source "${HERE}/backup-crypto.sh"

# ── Env overrides ────────────────────────────────────────────────────────
BACKUP_ROOT="${BACKUP_ROOT:-/var/backups/flowstarter}"
SITES_DIR="${SITES_DIR:-/var/www/sites}"
ETC_DIR="${FLOWSTARTER_ETC_DIR:-/etc/flowstarter}"
PG_DUMP_ARGS="${PG_DUMP_ARGS:-}"
BACKUP_GPG_PASSPHRASE_FILE="${BACKUP_GPG_PASSPHRASE_FILE:-/etc/flowstarter/backup-gpg-passphrase}"
BACKUP_S3_BUCKET="${BACKUP_S3_BUCKET:-}"
BACKUP_S3_ENDPOINT="${BACKUP_S3_ENDPOINT:-}"
BACKUP_S3_PREFIX="${BACKUP_S3_PREFIX:-$(hostname 2>/dev/null || printf 'host')}"

# Named, documented defaults for the retention knobs, same pattern as
# capEur() in funnel-cost.ts: a magic number buried in the deletion logic
# below would be much easier to get wrong than a named constant with a
# fallback.
DEFAULT_KEEP_DAILY=7
DEFAULT_KEEP_WEEKLY=4

# Which containers hold a database worth dumping. Two alternations: every
# Supabase CLI stack (`supabase_db_<project_id>`, a host can in principle run
# more than one) and the Cal.com database, whose name is anchored at both ends
# because it is exactly one container, not a family.
DEFAULT_DB_CONTAINER_PATTERN='^supabase_db_|^flowstarter-cal-db$'
BACKUP_DB_CONTAINER_PATTERN="${BACKUP_DB_CONTAINER_PATTERN:-$DEFAULT_DB_CONTAINER_PATTERN}"

# What a container's Postgres user and database fall back to when the container
# does not say. Cal's container sets both to `calcom`, and guessing `postgres`
# there fails the dump with "role postgres does not exist", so the values are
# discovered per container rather than assumed — see dump_database().
DEFAULT_POSTGRES_USER=postgres
DEFAULT_POSTGRES_DB=postgres

# Containers whose own POSTGRES_USER must NOT be believed.
#
# The Supabase CLI stack's image sets `POSTGRES_USER=supabase_admin`, which is
# a superuser the socket asks for a password for; `postgres` is the role that
# is trusted over the local socket and the one every dump on this host has
# used since the job existed. Measured on fs-sites-01, 2026-09-13: taking the
# container at its word turned a working Supabase dump into `fe_sendauth: no
# password supplied` and a zero-byte file in the backup directory.
#
# So the rule is an exception list rather than blanket discovery, and it is a
# regex in a variable for the same reason the container pattern above is: a
# second stack, or a future image that fixes this, is an env change.
DEFAULT_TRUSTED_ROLE_CONTAINER_PATTERN='^supabase_db_'
BACKUP_TRUSTED_ROLE_CONTAINER_PATTERN="${BACKUP_TRUSTED_ROLE_CONTAINER_PATTERN:-$DEFAULT_TRUSTED_ROLE_CONTAINER_PATTERN}"

usage() {
  cat >&2 <<'EOF'
Usage: backup.sh

  Dumps every Supabase CLI stack's Postgres database and the self-hosted
  Cal.com database (both encrypted), tars $SITES_DIR (plaintext — it carries
  nothing secret) and $FLOWSTARTER_ETC_DIR (encrypted, excluding the gpg
  passphrase file itself), writes a sha256 manifest, and applies retention,
  all under $BACKUP_ROOT/<UTC date>/. See the header comment in this file for
  every env var it reads.
EOF
}

require_root() {
  local uid
  uid="$(id -u)"
  if [[ "$uid" -ne 0 ]]; then
    echo "backup.sh must be run as root (current uid: ${uid})." >&2
    exit 1
  fi
}

# ── Cleanup on failure ──────────────────────────────────────────────────────
#
# Every artifact is first written to "${dest}.partial" and only renamed to
# its final name once the producer (a pipeline, under `set -o pipefail`) has
# exited zero. CLEANUP_PATHS collects every ".partial" path in use during
# this run; on any non-zero exit, whatever is still there — because the run
# died before the rename — is removed, so a failed run never leaves a file
# indistinguishable from a finished one.
CLEANUP_PATHS=""

register_cleanup() {
  CLEANUP_PATHS="${CLEANUP_PATHS}${1}"$'\n'
}

cleanup_on_exit() {
  local rc=$?
  if [[ "$rc" -ne 0 ]]; then
    local p
    while IFS= read -r p; do
      [[ -z "$p" ]] && continue
      if [[ -e "$p" ]]; then
        echo "Cleaning up incomplete artifact: ${p}" >&2
        rm -f "$p"
      fi
    done <<<"$CLEANUP_PATHS"
  fi
  return "$rc"
}
trap cleanup_on_exit EXIT

keep_daily_count() {
  local raw="${BACKUP_KEEP_DAILY:-}"
  if [[ "$raw" =~ ^[0-9]+$ ]]; then
    printf '%s' "$raw"
  else
    printf '%s' "$DEFAULT_KEEP_DAILY"
  fi
}

keep_weekly_count() {
  local raw="${BACKUP_KEEP_WEEKLY:-}"
  if [[ "$raw" =~ ^[0-9]+$ ]]; then
    printf '%s' "$raw"
  else
    printf '%s' "$DEFAULT_KEEP_WEEKLY"
  fi
}

sha256_cmd() {
  local path="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$path"
  else
    shasum -a 256 "$path"
  fi
}

# Hashes a file and prints a `sha256sum -c`-compatible line with a path
# relative to the file's own directory, so the manifest still verifies after
# the whole dated directory is copied or moved somewhere else.
manifest_line_for() {
  local path="$1" dir name
  dir="$(dirname "$path")"
  name="$(basename "$path")"
  (cd "$dir" && sha256_cmd "$name")
}

# ── Database dumps ───────────────────────────────────────────────────────

# Containers are discovered by pattern rather than by name: a host can in
# principle run more than one Supabase CLI stack (`supabase_db_<project_id>`,
# this project's is `supabase_db_flowstarter`, see supabase/config.toml), and
# the Cal database is a second, differently-named container that must be
# dumped by the same nightly run. The pattern is a variable so neither name
# appears in the logic.
discover_stack_containers() {
  docker ps --format '{{.Names}}' | grep -E "$BACKUP_DB_CONTAINER_PATTERN" || true
}

# Asks a container what its own Postgres user and database are. The image sets
# these in its environment (that is how the entrypoint created the cluster in
# the first place), so `printenv` inside the container is the authoritative
# answer and needs no table of names kept in step by hand. An unset variable
# makes `printenv` exit non-zero, which is the caller's signal to fall back.
container_env_value() {
  local container="$1" key="$2"
  docker exec "$container" printenv "$key" 2>/dev/null || true
}

# Dumps one container's application database with `pg_dump` run INSIDE the
# container, custom format (-Fc, already compressed, so this is not gzipped
# again), and streams the dump straight through encrypt_stream into its
# final file — no plaintext dump ever touches this host's disk (security
# audit 2026-09-13, M2/F15).
#
# The user and the database are discovered per container rather than
# assumed: the Supabase CLI stack uses `postgres` for both, Cal uses
# `calcom` for both, and a dump that guessed wrong would fail with "role
# does not exist". See BACKUP_TRUSTED_ROLE_CONTAINER_PATTERN above for why
# the Supabase container's own POSTGRES_USER is deliberately not believed.
#
# Written first to "${out_file}.partial" and renamed only once the whole
# pipeline (dump AND encryption) has succeeded, per the cleanup contract
# above — this is also what keeps a failed dump from ever leaving a
# zero-byte or half-written "backup" that looks finished; there is no
# separate `rm -f "$out_file"` on failure the way an unencrypted, direct
# `>"$out_file"` redirect would need, because `$out_file` itself is never
# opened for writing until the `mv` below.
#
# PG_DUMP_ARGS is deliberately word-split (shellcheck disabled below) so an
# operator can add flags such as --exclude-table without this script needing to
# know about every possible pg_dump option.
dump_database_encrypted() {
  local container="$1" out_file="$2" user db
  if printf '%s\n' "$container" | grep -qE "$BACKUP_TRUSTED_ROLE_CONTAINER_PATTERN"; then
    # See BACKUP_TRUSTED_ROLE_CONTAINER_PATTERN: this container's own
    # POSTGRES_USER names a role that cannot connect without a password.
    user="$DEFAULT_POSTGRES_USER"
    db="$(container_env_value "$container" POSTGRES_DB)"
    db="${db:-$DEFAULT_POSTGRES_DB}"
  else
    user="$(container_env_value "$container" POSTGRES_USER)"
    db="$(container_env_value "$container" POSTGRES_DB)"
    user="${user:-$DEFAULT_POSTGRES_USER}"
    db="${db:-$DEFAULT_POSTGRES_DB}"
  fi

  local partial="${out_file}.partial"
  register_cleanup "$partial"
  echo "Dumping ${container} (user: ${user}, database: ${db}) -> ${out_file} (encrypted with ${ENC_TOOL})"
  # `-w` because this runs from a nightly timer with no terminal: without it a
  # role that needs a password makes pg_dump sit on a prompt nobody will ever
  # answer, and the unit hangs instead of failing.
  # shellcheck disable=SC2086
  if ! docker exec "$container" pg_dump -w -U "$user" -Fc $PG_DUMP_ARGS "$db" |
    encrypt_stream >"$partial"; then
    echo "BACKUP FAILED: pg_dump of ${container} (user: ${user}, database: ${db}) did not succeed." >&2
    return 1
  fi
  chmod 0600 "$partial"
  mv "$partial" "$out_file"
}

# ── Encrypted tar archive ────────────────────────────────────────────────

# Tars $src_dir and streams it straight through encrypt_stream into
# $out_file — never a plaintext tarball on disk, not even momentarily.
# $exclude_name, if non-empty, is excluded from the tar by name relative to
# $src_dir (used to keep the gpg passphrase file out of the /etc tarball it
# would otherwise be encrypted inside of).
tar_encrypted() {
  local src_dir="$1" out_file="$2" exclude_name="${3:-}"
  local partial="${out_file}.partial"
  register_cleanup "$partial"
  local parent base
  parent="$(dirname "$src_dir")"
  base="$(basename "$src_dir")"
  echo "Archiving ${src_dir} -> ${out_file} (encrypted with ${ENC_TOOL})"
  if [[ -n "$exclude_name" ]]; then
    tar --exclude="${base}/${exclude_name}" -cz -C "$parent" "$base" |
      encrypt_stream >"$partial"
  else
    tar -cz -C "$parent" "$base" | encrypt_stream >"$partial"
  fi
  chmod 0600 "$partial"
  mv "$partial" "$out_file"
}

# ── Retention ────────────────────────────────────────────────────────────

retention_apply() {
  local keep_daily keep_weekly
  keep_daily="$(keep_daily_count)"
  keep_weekly="$(keep_weekly_count)"

  # Newline-separated lists rather than bash arrays throughout this
  # function, matching deploy-slot.sh and supabase-stack.sh (neither uses an
  # array): it sidesteps every bash-version quirk around expanding a
  # possibly-empty array under `set -u`, at the cost of a few more `sed`/
  # `grep` calls, which is a fine trade for a script that runs once a night.
  #
  # `-printf` is GNU-find-only; piping through `xargs -n1 basename` gets the
  # same bare directory names on both the GNU find on the real host and the
  # BSD find this runs under in tests.
  local dirs
  # shellcheck disable=SC2038 # the -name glob restricts results to
  # YYYY-MM-DD, a fixed digit-and-hyphen shape with no room for a filename
  # `xargs` could ever misparse.
  dirs="$(
    find "$BACKUP_ROOT" -maxdepth 1 -mindepth 1 -type d \
      -name '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' 2>/dev/null |
      xargs -n1 basename |
      sort -r
  )"
  if [[ -z "$dirs" ]]; then
    return 0
  fi

  local keep_list
  keep_list="$(printf '%s\n' "$dirs" | head -n "$keep_daily")"

  local rest rest_count
  rest="$(printf '%s\n' "$dirs" | tail -n "+$((keep_daily + 1))")"
  if [[ -z "$rest" ]]; then
    rest_count=0
  else
    rest_count="$(printf '%s\n' "$rest" | wc -l | tr -d ' ')"
  fi

  # `rest` is still newest-first. Group it into runs of 7 (one nightly
  # backup per elapsed day, so a run of 7 approximates one calendar week)
  # and keep the oldest directory in each of the most recent `keep_weekly`
  # runs; that is the last line of each 7-wide slice. This is simpler than
  # parsing a weekday or an ISO week number out of a directory name, and
  # converges to the same roughly-weekly cadence in practice.
  local group=0 start end line
  while [[ "$group" -lt "$keep_weekly" ]]; do
    start=$((group * 7))
    [[ "$start" -ge "$rest_count" ]] && break
    end=$((start + 6))
    [[ "$end" -ge "$rest_count" ]] && end=$((rest_count - 1))
    line="$(printf '%s\n' "$rest" | sed -n "$((end + 1))p")"
    keep_list="$(printf '%s\n%s\n' "$keep_list" "$line")"
    group=$((group + 1))
  done

  local d
  while IFS= read -r d; do
    [[ -z "$d" ]] && continue
    if printf '%s\n' "$keep_list" | grep -qxF "$d"; then
      continue
    fi
    echo "Retention: removing ${BACKUP_ROOT}/${d} (beyond keep-daily=${keep_daily}, keep-weekly=${keep_weekly})"
    rm -rf "${BACKUP_ROOT:?}/${d:?}"
  done <<<"$dirs"
}

# ── Optional S3-compatible upload ───────────────────────────────────────────

# Prefers rclone over aws when both are on PATH: rclone is what the Hetzner
# image actually installs for this job; aws is only a fallback for a box
# that ended up with the AWS CLI instead. Returns non-zero only when an
# upload was attempted and failed; a skip (no BACKUP_S3_BUCKET) is success.
upload_to_s3() {
  local dest_dir="$1"

  if [[ -z "$BACKUP_S3_BUCKET" ]]; then
    echo "BACKUP_S3_BUCKET is not set; skipping remote upload."
    return 0
  fi

  local remote_path
  remote_path="${BACKUP_S3_PREFIX}/$(basename "$dest_dir")"

  if command -v rclone >/dev/null 2>&1; then
    local rclone_ok=1
    if [[ -n "$BACKUP_S3_ENDPOINT" ]]; then
      rclone copy "$dest_dir" "${BACKUP_S3_BUCKET}:${remote_path}" --s3-endpoint "$BACKUP_S3_ENDPOINT" || rclone_ok=0
    else
      rclone copy "$dest_dir" "${BACKUP_S3_BUCKET}:${remote_path}" || rclone_ok=0
    fi
    if [[ "$rclone_ok" -eq 1 ]]; then
      echo "Uploaded ${dest_dir} to ${BACKUP_S3_BUCKET}:${remote_path} via rclone."
      return 0
    fi
    echo "BACKUP UPLOAD FAILED: rclone could not copy ${dest_dir} to ${BACKUP_S3_BUCKET}:${remote_path}. The local backup is intact; investigate the journal for this unit and retry the upload by hand." >&2
    return 1
  fi

  if command -v aws >/dev/null 2>&1; then
    local aws_ok=1
    if [[ -n "$BACKUP_S3_ENDPOINT" ]]; then
      aws s3 cp "$dest_dir" "s3://${BACKUP_S3_BUCKET}/${remote_path}" --recursive --endpoint-url "$BACKUP_S3_ENDPOINT" || aws_ok=0
    else
      aws s3 cp "$dest_dir" "s3://${BACKUP_S3_BUCKET}/${remote_path}" --recursive || aws_ok=0
    fi
    if [[ "$aws_ok" -eq 1 ]]; then
      echo "Uploaded ${dest_dir} to s3://${BACKUP_S3_BUCKET}/${remote_path} via aws."
      return 0
    fi
    echo "BACKUP UPLOAD FAILED: aws could not copy ${dest_dir} to s3://${BACKUP_S3_BUCKET}/${remote_path}. The local backup is intact; investigate the journal for this unit and retry the upload by hand." >&2
    return 1
  fi

  echo "BACKUP_S3_BUCKET is set but neither rclone nor aws is on PATH; cannot upload." >&2
  return 1
}

# ── Main ─────────────────────────────────────────────────────────────────

main() {
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
  fi

  require_root

  # Restrictive by construction: every file and directory this script
  # creates from here on defaults to owner-only (0600 files, 0700 dirs)
  # regardless of whatever umask the environment (systemd, a login shell,
  # cron) handed it. Explicit chmods below are defence in depth for
  # directories/files that might pre-date this fix.
  umask 0077

  # Fail fast, before dumping a single byte: pick the encryption tool and
  # validate its configuration (in particular, the gpg passphrase file's
  # mode) up front rather than partway through the run.
  select_encryption_tool

  mkdir -p "$BACKUP_ROOT"
  chmod 0700 "$BACKUP_ROOT"

  local date_str dest_dir
  date_str="$(date -u +%Y-%m-%d)"
  dest_dir="${BACKUP_ROOT}/${date_str}"
  mkdir -p "$dest_dir"
  chmod 0700 "$dest_dir"
  echo "Starting backup into ${dest_dir}"

  # A newline-separated list rather than a bash array, same reasoning as
  # retention_apply(): no array means no bash-version-dependent behaviour
  # around expanding one that turns out to be empty.
  local artifacts=""

  local containers container out_file
  containers="$(discover_stack_containers)"
  if [[ -z "$containers" ]]; then
    echo "No container matched ${BACKUP_DB_CONTAINER_PATTERN} on this host; skipping database dumps."
  fi
  while IFS= read -r container; do
    [[ -z "$container" ]] && continue
    out_file="${dest_dir}/db-${container}.dump.${ENC_EXT}"
    dump_database_encrypted "$container" "$out_file"
    artifacts="${artifacts}${out_file}"$'\n'
  done <<<"$containers"

  if [[ -d "$SITES_DIR" ]]; then
    local sites_tar="${dest_dir}/sites.tar.gz"
    local sites_partial="${sites_tar}.partial"
    register_cleanup "$sites_partial"
    echo "Archiving ${SITES_DIR} -> ${sites_tar}"
    tar -czf "$sites_partial" -C "$(dirname "$SITES_DIR")" "$(basename "$SITES_DIR")"
    chmod 0600 "$sites_partial"
    mv "$sites_partial" "$sites_tar"
    artifacts="${artifacts}${sites_tar}"$'\n'
  else
    echo "SITES_DIR (${SITES_DIR}) does not exist; skipping site archive."
  fi

  if [[ -d "$ETC_DIR" ]]; then
    local etc_tar="${dest_dir}/etc-flowstarter.tar.gz.${ENC_EXT}"
    # Never ship the gpg passphrase inside the very tarball it (or a
    # sibling artifact) is encrypted with — see the module doc comment
    # (security audit M2/F15). Only excluded when the passphrase file is
    # actually inside ETC_DIR; a passphrase file kept elsewhere (the
    # recommended long-term fix — see the audit's "move the passphrase off
    # this host") needs no special-casing here at all.
    local exclude_name=""
    case "$BACKUP_GPG_PASSPHRASE_FILE" in
      "${ETC_DIR}"/*)
        exclude_name="${BACKUP_GPG_PASSPHRASE_FILE#"${ETC_DIR}"/}"
        ;;
    esac
    tar_encrypted "$ETC_DIR" "$etc_tar" "$exclude_name"
    artifacts="${artifacts}${etc_tar}"$'\n'
  else
    echo "ETC_DIR (${ETC_DIR}) does not exist; skipping secrets archive."
  fi

  echo "Writing manifest.sha256 ..."
  local manifest="${dest_dir}/manifest.sha256"
  : >"$manifest"
  chmod 0600 "$manifest"
  local artifact
  while IFS= read -r artifact; do
    [[ -z "$artifact" ]] && continue
    manifest_line_for "$artifact" >>"$manifest"
  done <<<"$artifacts"
  echo "Wrote ${manifest}"

  echo "Applying retention (keep-daily=$(keep_daily_count), keep-weekly=$(keep_weekly_count)) ..."
  retention_apply

  local upload_failed=0
  if ! upload_to_s3 "$dest_dir"; then
    upload_failed=1
  fi

  echo "Backup complete: ${dest_dir}"
  if [[ "$upload_failed" -eq 1 ]]; then
    echo "backup.sh: exiting non-zero because the remote upload failed (the local backup above succeeded)." >&2
    exit 1
  fi
}

main "$@"
